stages:
  - notify

notify_mattermost:
  stage: notify
  tags:
    - docker
    - runner
    - gitlab
  script:
    - apt-get update && apt-get install -y curl jq
    - >
      if [ -n "$CI_MERGE_REQUEST_IID" ]; then 
        curl -X POST -H "Content-Type: application/json" \
          -d "{
            \"text\": \"🔀 *새로운 Merge Request가 생성되었습니다!* 🎉\\n
            **프로젝트:** \`$CI_PROJECT_NAME\`\\n
            **작성자:** \`$GITLAB_USER_LOGIN\`\\n
            **브랜치:** \`$CI_COMMIT_REF_NAME\`\\n
            **MR 제목:** \\\"${CI_MERGE_REQUEST_TITLE:-"제목 없음"}\\\"\\n
            [**Merge Request 보기**]($CI_PROJECT_URL/-/merge_requests/$CI_MERGE_REQUEST_IID)"
          }" https://meeting.ssafy.com/hooks/9ecrs1m8ybbtfpa5dxsms8n4zo
      else
        echo "❌ MR 정보 없음"
      fi

notify_issue:
  stage: notify
  tags:
    - docker
    - runner
    - gitlab
  script:
    - apt-get update && apt-get install -y curl jq
    - echo "CI_JOB_ID = $CI_JOB_ID"
    - >
      if [ -n "$CI_COMMIT_MESSAGE" ]; then 
        MESSAGE=$(echo "$CI_COMMIT_MESSAGE" | iconv -f UTF-8 -t UTF-8 | jq -Rs .)
        curl -X POST -H "Content-Type: application/json" \
          -d "{
            \"text\": \"📌 *새로운 이슈가 생성되었습니다!* 📝\\n
            **프로젝트:** \`$CI_PROJECT_NAME\`\\n
            **작성자:** \`$GITLAB_USER_LOGIN\`\\n
            **이슈 제목:** ${MESSAGE}\\n
            [**이슈 보기**]($CI_PROJECT_URL/-/issues/$CI_JOB_ID)"
          }" https://meeting.ssafy.com/hooks/9ecrs1m8ybbtfpa5dxsms8n4zo
      else
        echo "❌ 이슈 정보 없음"
      fi
