stages:
  - notify

# Merge Request 발생 시 Mattermost로 알림 전송
notify_mattermost:
  stage: notify
  tags: 
    - docker
    - runner
    - gitlab
  script:
    - >
      if [ -n "$CI_MERGE_REQUEST_IID" ]; then 
        curl -X POST -H "Content-Type: application/json" \
          -d '{
            "text": "🔀 *새로운 Merge Request가 생성되었습니다!* 🎉\n
            **Related Issues**\n
            - resolved #'"$CI_MERGE_REQUEST_IID"' (`gitlab`)\n\n
            ✅ **작업 내용**\n
            '"$(echo "$CI_COMMIT_MESSAGE" | sed 's/- /- [x] /g')"'\n\n
            📌 **PR Point**\n
            - '"$(echo "$CI_COMMIT_MESSAGE" | sed -n '/PR Point:/,$p' | sed 's/- /- /g')"' \n\n
            [**➡️ Merge Request 보기**]('$CI_PROJECT_URL/-/merge_requests/$CI_MERGE_REQUEST_IID')"
          }' https://meeting.ssafy.com/hooks/9ecrs1m8ybbtfpa5dxsms8n4zo
      else
        echo "❌ MR 정보 없음"
      fi

# 이슈 발생 시 Mattermost로 알림 전송
notify_issue:
  stage: notify
  tags:
    - docker
    - runner
    - gitlab
  script:
    - >
      if [ -n "$CI_COMMIT_MESSAGE" ]; then 
        curl -X POST -H "Content-Type: application/json" \
          -d '{
            "text": "📌 *새로운 이슈가 생성되었습니다!* 📝\n
            **프로젝트:** `'$CI_PROJECT_NAME'`\n
            **작성자:** `'$GITLAB_USER_LOGIN'`\n\n
            **👉 어떤 기능인가요?**\n
            '"$(echo "$CI_COMMIT_MESSAGE" | sed -n '/어떤 기능인가요:/,$p' | sed 's/- /- /g')"' \n\n
            ✅ **To Dos**\n
            '"$(echo "$CI_COMMIT_MESSAGE" | sed -n '/To Dos:/,$p' | sed 's/- /- [ ] /g')"' \n\n
            [**➡️ 이슈 보기**]('$CI_PROJECT_URL/-/issues/$CI_JOB_ID')"
          }' https://meeting.ssafy.com/hooks/9ecrs1m8ybbtfpa5dxsms8n4zo
      else
        echo "❌ 이슈 정보 없음"
      fi
